spring:
  datasource:
    url: jdbc:mysql://localhost:3306/btc?serverTimezone=Asia/Seoul
    username: jay
    password: jay
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


jwt:
  secret: 6ouCAVlTs2RpGKctFeqtKDC3IzQfIuNSZogfQuGYgvo

